#ifndef _ENUMAPI_H_
#define _ENUMAPI_H_


/*  OBSERVATIONS */ 
typedef enum { 
      test_mpre202p_pressureReading_pr02Crack,
      test_mpre202p_pressureReading_pressurizationRate_upperBound,
      test_mpre202p_pressureReading_pressurizationRate_lowerBound,
      test_mpre202p_pressureReading_boiloffRate_upperBound,
      test_mpre202p_pressureReading_boiloffRate_lowerBound,
      test_mpre202p_pressureReading_bleedRate_upperBound,
      test_mpre202p_pressureReading_bleedRate_lowerBound,
      test_mpre202p_pressureReading_ventingRate_upperBound,
      test_mpre202p_pressureReading_ventingRate_lowerBound,
      test_mpre212p_pressureReading_pr02Crack,
      test_mpre212p_pressureReading_pressurizationRate_upperBound,
      test_mpre212p_pressureReading_pressurizationRate_lowerBound,
      test_mpre212p_pressureReading_boiloffRate_upperBound,
      test_mpre212p_pressureReading_boiloffRate_lowerBound,
      test_mpre212p_pressureReading_bleedRate_upperBound,
      test_mpre212p_pressureReading_bleedRate_lowerBound,
      test_mpre212p_pressureReading_ventingRate_upperBound,
      test_mpre212p_pressureReading_ventingRate_lowerBound,
      test_mpre222p_pressureReading_pr02Crack,
      test_mpre222p_pressureReading_pressurizationRate_upperBound,
      test_mpre222p_pressureReading_pressurizationRate_lowerBound,
      test_mpre222p_pressureReading_boiloffRate_upperBound,
      test_mpre222p_pressureReading_boiloffRate_lowerBound,
      test_mpre222p_pressureReading_bleedRate_upperBound,
      test_mpre222p_pressureReading_bleedRate_lowerBound,
      test_mpre222p_pressureReading_ventingRate_upperBound,
      test_mpre222p_pressureReading_ventingRate_lowerBound,
      test_mpre103p_pressureReading_rg11_upperBound,
      test_mpre103p_pressureReading_rg11_lowerBound,
      test_mpre103p_pressureReading_rg01_upperBound,
      test_mpre103p_pressureReading_rg01_lowerBound,
      test_mpre102p_pressureReading_rg21_upperBound,
      test_mpre102p_pressureReading_rg21_lowerBound,
      test_mpre102p_pressureReading_rg02_upperBound,
      test_mpre102p_pressureReading_rg02_lowerBound,
      test_mpre101p_pressureReading_rg11_upperBound,
      test_mpre101p_pressureReading_rg11_lowerBound,
      test_mpre101p_pressureReading_rg01_upperBound,
      test_mpre101p_pressureReading_rg01_lowerBound,
      test_mrtd103t_temperatureReading_tankMixture_upperBound,
      test_mrtd103t_temperatureReading_tankMixture_lowerBound,
      test_mrtd103t_temperatureReading_gHe_upperBound,
      test_mrtd103t_temperatureReading_gHe_lowerBound,
      test_sv03_microSwitch,
      test_sv31_microSwitch,
      test_mpre104p_pressureReading_rg11_upperBound,
      test_mpre104p_pressureReading_rg11_lowerBound,
      test_mpre104p_pressureReading_rg01_upperBound,
      test_mpre104p_pressureReading_rg01_lowerBound,
      test_mrtd104t_temperatureReading_tankMixture_upperBound,
      test_mrtd104t_temperatureReading_tankMixture_lowerBound,
      test_mrtd104t_temperatureReading_gHe_upperBound,
      test_mrtd104t_temperatureReading_gHe_lowerBound,
      test_mrtd201t_temperatureReading_lO2_upperBound,
      test_mrtd201t_temperatureReading_lO2_lowerBound,
      test_mpre107p_pressureReading_rg21_upperBound,
      test_mpre107p_pressureReading_rg21_lowerBound,
      test_mpre107p_pressureReading_rg02_upperBound,
      test_mpre107p_pressureReading_rg02_lowerBound,
      test_mrtd203t_temperatureReading_tankMixture_upperBound,
      test_mrtd203t_temperatureReading_tankMixture_lowerBound,
      test_mrtd203t_temperatureReading_ambient_upperBound,
      test_mrtd203t_temperatureReading_ambient_lowerBound,
      test_mpre204p_pressureReading_bleedRate_upperBound,
      test_mpre204p_pressureReading_bleedRate_lowerBound,
      test_mrtd204t_temperatureReading_lO2_upperBound,
      test_mrtd204t_temperatureReading_lO2_lowerBound,
      test_mpre205p_pressureReading_bleedRate_upperBound,
      test_mpre205p_pressureReading_bleedRate_lowerBound,
      test_mrtd205t_temperatureReading_lO2_upperBound,
      test_mrtd205t_temperatureReading_lO2_lowerBound,
      test_pv03_positionIndicator_openIndicator,
      test_pv03_positionIndicator_closedIndicator,
      test_mpre201p_pressureReading_pr02Crack,
      test_mpre201p_pressureReading_pressurizationRate_upperBound,
      test_mpre201p_pressureReading_pressurizationRate_lowerBound,
      test_mpre201p_pressureReading_boiloffRate_upperBound,
      test_mpre201p_pressureReading_boiloffRate_lowerBound,
      test_mpre201p_pressureReading_bleedRate_upperBound,
      test_mpre201p_pressureReading_bleedRate_lowerBound,
      test_mpre201p_pressureReading_ventingRate_upperBound,
      test_mpre201p_pressureReading_ventingRate_lowerBound,
      test_aftLO2_lO2Level,
      NUM_observation_types
} observation_types;


/*  OBSERVATION TYPES */ 
enum test_mpre202p_pressureReading_pr02Crack_values { test_mpre202p_pressureReading_pr02Crack_aboveThreshold, test_mpre202p_pressureReading_pr02Crack_belowThreshold };
enum test_mpre202p_pressureReading_pressurizationRate_upperBound_values { test_mpre202p_pressureReading_pressurizationRate_upperBound_aboveThreshold, test_mpre202p_pressureReading_pressurizationRate_upperBound_belowThreshold };
enum test_mpre202p_pressureReading_pressurizationRate_lowerBound_values { test_mpre202p_pressureReading_pressurizationRate_lowerBound_aboveThreshold, test_mpre202p_pressureReading_pressurizationRate_lowerBound_belowThreshold };
enum test_mpre202p_pressureReading_boiloffRate_upperBound_values { test_mpre202p_pressureReading_boiloffRate_upperBound_aboveThreshold, test_mpre202p_pressureReading_boiloffRate_upperBound_belowThreshold };
enum test_mpre202p_pressureReading_boiloffRate_lowerBound_values { test_mpre202p_pressureReading_boiloffRate_lowerBound_aboveThreshold, test_mpre202p_pressureReading_boiloffRate_lowerBound_belowThreshold };
enum test_mpre202p_pressureReading_bleedRate_upperBound_values { test_mpre202p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre202p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre202p_pressureReading_bleedRate_lowerBound_values { test_mpre202p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre202p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mpre202p_pressureReading_ventingRate_upperBound_values { test_mpre202p_pressureReading_ventingRate_upperBound_aboveThreshold, test_mpre202p_pressureReading_ventingRate_upperBound_belowThreshold };
enum test_mpre202p_pressureReading_ventingRate_lowerBound_values { test_mpre202p_pressureReading_ventingRate_lowerBound_aboveThreshold, test_mpre202p_pressureReading_ventingRate_lowerBound_belowThreshold };
enum test_mpre212p_pressureReading_pr02Crack_values { test_mpre212p_pressureReading_pr02Crack_aboveThreshold, test_mpre212p_pressureReading_pr02Crack_belowThreshold };
enum test_mpre212p_pressureReading_pressurizationRate_upperBound_values { test_mpre212p_pressureReading_pressurizationRate_upperBound_aboveThreshold, test_mpre212p_pressureReading_pressurizationRate_upperBound_belowThreshold };
enum test_mpre212p_pressureReading_pressurizationRate_lowerBound_values { test_mpre212p_pressureReading_pressurizationRate_lowerBound_aboveThreshold, test_mpre212p_pressureReading_pressurizationRate_lowerBound_belowThreshold };
enum test_mpre212p_pressureReading_boiloffRate_upperBound_values { test_mpre212p_pressureReading_boiloffRate_upperBound_aboveThreshold, test_mpre212p_pressureReading_boiloffRate_upperBound_belowThreshold };
enum test_mpre212p_pressureReading_boiloffRate_lowerBound_values { test_mpre212p_pressureReading_boiloffRate_lowerBound_aboveThreshold, test_mpre212p_pressureReading_boiloffRate_lowerBound_belowThreshold };
enum test_mpre212p_pressureReading_bleedRate_upperBound_values { test_mpre212p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre212p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre212p_pressureReading_bleedRate_lowerBound_values { test_mpre212p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre212p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mpre212p_pressureReading_ventingRate_upperBound_values { test_mpre212p_pressureReading_ventingRate_upperBound_aboveThreshold, test_mpre212p_pressureReading_ventingRate_upperBound_belowThreshold };
enum test_mpre212p_pressureReading_ventingRate_lowerBound_values { test_mpre212p_pressureReading_ventingRate_lowerBound_aboveThreshold, test_mpre212p_pressureReading_ventingRate_lowerBound_belowThreshold };
enum test_mpre222p_pressureReading_pr02Crack_values { test_mpre222p_pressureReading_pr02Crack_aboveThreshold, test_mpre222p_pressureReading_pr02Crack_belowThreshold };
enum test_mpre222p_pressureReading_pressurizationRate_upperBound_values { test_mpre222p_pressureReading_pressurizationRate_upperBound_aboveThreshold, test_mpre222p_pressureReading_pressurizationRate_upperBound_belowThreshold };
enum test_mpre222p_pressureReading_pressurizationRate_lowerBound_values { test_mpre222p_pressureReading_pressurizationRate_lowerBound_aboveThreshold, test_mpre222p_pressureReading_pressurizationRate_lowerBound_belowThreshold };
enum test_mpre222p_pressureReading_boiloffRate_upperBound_values { test_mpre222p_pressureReading_boiloffRate_upperBound_aboveThreshold, test_mpre222p_pressureReading_boiloffRate_upperBound_belowThreshold };
enum test_mpre222p_pressureReading_boiloffRate_lowerBound_values { test_mpre222p_pressureReading_boiloffRate_lowerBound_aboveThreshold, test_mpre222p_pressureReading_boiloffRate_lowerBound_belowThreshold };
enum test_mpre222p_pressureReading_bleedRate_upperBound_values { test_mpre222p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre222p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre222p_pressureReading_bleedRate_lowerBound_values { test_mpre222p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre222p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mpre222p_pressureReading_ventingRate_upperBound_values { test_mpre222p_pressureReading_ventingRate_upperBound_aboveThreshold, test_mpre222p_pressureReading_ventingRate_upperBound_belowThreshold };
enum test_mpre222p_pressureReading_ventingRate_lowerBound_values { test_mpre222p_pressureReading_ventingRate_lowerBound_aboveThreshold, test_mpre222p_pressureReading_ventingRate_lowerBound_belowThreshold };
enum test_mpre103p_pressureReading_rg11_upperBound_values { test_mpre103p_pressureReading_rg11_upperBound_aboveThreshold, test_mpre103p_pressureReading_rg11_upperBound_belowThreshold };
enum test_mpre103p_pressureReading_rg11_lowerBound_values { test_mpre103p_pressureReading_rg11_lowerBound_aboveThreshold, test_mpre103p_pressureReading_rg11_lowerBound_belowThreshold };
enum test_mpre103p_pressureReading_rg01_upperBound_values { test_mpre103p_pressureReading_rg01_upperBound_aboveThreshold, test_mpre103p_pressureReading_rg01_upperBound_belowThreshold };
enum test_mpre103p_pressureReading_rg01_lowerBound_values { test_mpre103p_pressureReading_rg01_lowerBound_aboveThreshold, test_mpre103p_pressureReading_rg01_lowerBound_belowThreshold };
enum test_mpre102p_pressureReading_rg21_upperBound_values { test_mpre102p_pressureReading_rg21_upperBound_aboveThreshold, test_mpre102p_pressureReading_rg21_upperBound_belowThreshold };
enum test_mpre102p_pressureReading_rg21_lowerBound_values { test_mpre102p_pressureReading_rg21_lowerBound_aboveThreshold, test_mpre102p_pressureReading_rg21_lowerBound_belowThreshold };
enum test_mpre102p_pressureReading_rg02_upperBound_values { test_mpre102p_pressureReading_rg02_upperBound_aboveThreshold, test_mpre102p_pressureReading_rg02_upperBound_belowThreshold };
enum test_mpre102p_pressureReading_rg02_lowerBound_values { test_mpre102p_pressureReading_rg02_lowerBound_aboveThreshold, test_mpre102p_pressureReading_rg02_lowerBound_belowThreshold };
enum test_mpre101p_pressureReading_rg11_upperBound_values { test_mpre101p_pressureReading_rg11_upperBound_aboveThreshold, test_mpre101p_pressureReading_rg11_upperBound_belowThreshold };
enum test_mpre101p_pressureReading_rg11_lowerBound_values { test_mpre101p_pressureReading_rg11_lowerBound_aboveThreshold, test_mpre101p_pressureReading_rg11_lowerBound_belowThreshold };
enum test_mpre101p_pressureReading_rg01_upperBound_values { test_mpre101p_pressureReading_rg01_upperBound_aboveThreshold, test_mpre101p_pressureReading_rg01_upperBound_belowThreshold };
enum test_mpre101p_pressureReading_rg01_lowerBound_values { test_mpre101p_pressureReading_rg01_lowerBound_aboveThreshold, test_mpre101p_pressureReading_rg01_lowerBound_belowThreshold };
enum test_mrtd103t_temperatureReading_tankMixture_upperBound_values { test_mrtd103t_temperatureReading_tankMixture_upperBound_aboveThreshold, test_mrtd103t_temperatureReading_tankMixture_upperBound_belowThreshold };
enum test_mrtd103t_temperatureReading_tankMixture_lowerBound_values { test_mrtd103t_temperatureReading_tankMixture_lowerBound_aboveThreshold, test_mrtd103t_temperatureReading_tankMixture_lowerBound_belowThreshold };
enum test_mrtd103t_temperatureReading_gHe_upperBound_values { test_mrtd103t_temperatureReading_gHe_upperBound_aboveThreshold, test_mrtd103t_temperatureReading_gHe_upperBound_belowThreshold };
enum test_mrtd103t_temperatureReading_gHe_lowerBound_values { test_mrtd103t_temperatureReading_gHe_lowerBound_aboveThreshold, test_mrtd103t_temperatureReading_gHe_lowerBound_belowThreshold };
enum test_sv03_microSwitch_values { test_sv03_microSwitch_open, test_sv03_microSwitch_notOpen };
enum test_sv31_microSwitch_values { test_sv31_microSwitch_open, test_sv31_microSwitch_notOpen };
enum test_mpre104p_pressureReading_rg11_upperBound_values { test_mpre104p_pressureReading_rg11_upperBound_aboveThreshold, test_mpre104p_pressureReading_rg11_upperBound_belowThreshold };
enum test_mpre104p_pressureReading_rg11_lowerBound_values { test_mpre104p_pressureReading_rg11_lowerBound_aboveThreshold, test_mpre104p_pressureReading_rg11_lowerBound_belowThreshold };
enum test_mpre104p_pressureReading_rg01_upperBound_values { test_mpre104p_pressureReading_rg01_upperBound_aboveThreshold, test_mpre104p_pressureReading_rg01_upperBound_belowThreshold };
enum test_mpre104p_pressureReading_rg01_lowerBound_values { test_mpre104p_pressureReading_rg01_lowerBound_aboveThreshold, test_mpre104p_pressureReading_rg01_lowerBound_belowThreshold };
enum test_mrtd104t_temperatureReading_tankMixture_upperBound_values { test_mrtd104t_temperatureReading_tankMixture_upperBound_aboveThreshold, test_mrtd104t_temperatureReading_tankMixture_upperBound_belowThreshold };
enum test_mrtd104t_temperatureReading_tankMixture_lowerBound_values { test_mrtd104t_temperatureReading_tankMixture_lowerBound_aboveThreshold, test_mrtd104t_temperatureReading_tankMixture_lowerBound_belowThreshold };
enum test_mrtd104t_temperatureReading_gHe_upperBound_values { test_mrtd104t_temperatureReading_gHe_upperBound_aboveThreshold, test_mrtd104t_temperatureReading_gHe_upperBound_belowThreshold };
enum test_mrtd104t_temperatureReading_gHe_lowerBound_values { test_mrtd104t_temperatureReading_gHe_lowerBound_aboveThreshold, test_mrtd104t_temperatureReading_gHe_lowerBound_belowThreshold };
enum test_mrtd201t_temperatureReading_lO2_upperBound_values { test_mrtd201t_temperatureReading_lO2_upperBound_aboveThreshold, test_mrtd201t_temperatureReading_lO2_upperBound_belowThreshold };
enum test_mrtd201t_temperatureReading_lO2_lowerBound_values { test_mrtd201t_temperatureReading_lO2_lowerBound_aboveThreshold, test_mrtd201t_temperatureReading_lO2_lowerBound_belowThreshold };
enum test_mpre107p_pressureReading_rg21_upperBound_values { test_mpre107p_pressureReading_rg21_upperBound_aboveThreshold, test_mpre107p_pressureReading_rg21_upperBound_belowThreshold };
enum test_mpre107p_pressureReading_rg21_lowerBound_values { test_mpre107p_pressureReading_rg21_lowerBound_aboveThreshold, test_mpre107p_pressureReading_rg21_lowerBound_belowThreshold };
enum test_mpre107p_pressureReading_rg02_upperBound_values { test_mpre107p_pressureReading_rg02_upperBound_aboveThreshold, test_mpre107p_pressureReading_rg02_upperBound_belowThreshold };
enum test_mpre107p_pressureReading_rg02_lowerBound_values { test_mpre107p_pressureReading_rg02_lowerBound_aboveThreshold, test_mpre107p_pressureReading_rg02_lowerBound_belowThreshold };
enum test_mrtd203t_temperatureReading_tankMixture_upperBound_values { test_mrtd203t_temperatureReading_tankMixture_upperBound_aboveThreshold, test_mrtd203t_temperatureReading_tankMixture_upperBound_belowThreshold };
enum test_mrtd203t_temperatureReading_tankMixture_lowerBound_values { test_mrtd203t_temperatureReading_tankMixture_lowerBound_aboveThreshold, test_mrtd203t_temperatureReading_tankMixture_lowerBound_belowThreshold };
enum test_mrtd203t_temperatureReading_ambient_upperBound_values { test_mrtd203t_temperatureReading_ambient_upperBound_aboveThreshold, test_mrtd203t_temperatureReading_ambient_upperBound_belowThreshold };
enum test_mrtd203t_temperatureReading_ambient_lowerBound_values { test_mrtd203t_temperatureReading_ambient_lowerBound_aboveThreshold, test_mrtd203t_temperatureReading_ambient_lowerBound_belowThreshold };
enum test_mpre204p_pressureReading_bleedRate_upperBound_values { test_mpre204p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre204p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre204p_pressureReading_bleedRate_lowerBound_values { test_mpre204p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre204p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mrtd204t_temperatureReading_lO2_upperBound_values { test_mrtd204t_temperatureReading_lO2_upperBound_aboveThreshold, test_mrtd204t_temperatureReading_lO2_upperBound_belowThreshold };
enum test_mrtd204t_temperatureReading_lO2_lowerBound_values { test_mrtd204t_temperatureReading_lO2_lowerBound_aboveThreshold, test_mrtd204t_temperatureReading_lO2_lowerBound_belowThreshold };
enum test_mpre205p_pressureReading_bleedRate_upperBound_values { test_mpre205p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre205p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre205p_pressureReading_bleedRate_lowerBound_values { test_mpre205p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre205p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mrtd205t_temperatureReading_lO2_upperBound_values { test_mrtd205t_temperatureReading_lO2_upperBound_aboveThreshold, test_mrtd205t_temperatureReading_lO2_upperBound_belowThreshold };
enum test_mrtd205t_temperatureReading_lO2_lowerBound_values { test_mrtd205t_temperatureReading_lO2_lowerBound_aboveThreshold, test_mrtd205t_temperatureReading_lO2_lowerBound_belowThreshold };
enum test_pv03_positionIndicator_openIndicator_values { test_pv03_positionIndicator_openIndicator_open, test_pv03_positionIndicator_openIndicator_notOpen };
enum test_pv03_positionIndicator_closedIndicator_values { test_pv03_positionIndicator_closedIndicator_closed, test_pv03_positionIndicator_closedIndicator_notClosed };
enum test_mpre201p_pressureReading_pr02Crack_values { test_mpre201p_pressureReading_pr02Crack_aboveThreshold, test_mpre201p_pressureReading_pr02Crack_belowThreshold };
enum test_mpre201p_pressureReading_pressurizationRate_upperBound_values { test_mpre201p_pressureReading_pressurizationRate_upperBound_aboveThreshold, test_mpre201p_pressureReading_pressurizationRate_upperBound_belowThreshold };
enum test_mpre201p_pressureReading_pressurizationRate_lowerBound_values { test_mpre201p_pressureReading_pressurizationRate_lowerBound_aboveThreshold, test_mpre201p_pressureReading_pressurizationRate_lowerBound_belowThreshold };
enum test_mpre201p_pressureReading_boiloffRate_upperBound_values { test_mpre201p_pressureReading_boiloffRate_upperBound_aboveThreshold, test_mpre201p_pressureReading_boiloffRate_upperBound_belowThreshold };
enum test_mpre201p_pressureReading_boiloffRate_lowerBound_values { test_mpre201p_pressureReading_boiloffRate_lowerBound_aboveThreshold, test_mpre201p_pressureReading_boiloffRate_lowerBound_belowThreshold };
enum test_mpre201p_pressureReading_bleedRate_upperBound_values { test_mpre201p_pressureReading_bleedRate_upperBound_aboveThreshold, test_mpre201p_pressureReading_bleedRate_upperBound_belowThreshold };
enum test_mpre201p_pressureReading_bleedRate_lowerBound_values { test_mpre201p_pressureReading_bleedRate_lowerBound_aboveThreshold, test_mpre201p_pressureReading_bleedRate_lowerBound_belowThreshold };
enum test_mpre201p_pressureReading_ventingRate_upperBound_values { test_mpre201p_pressureReading_ventingRate_upperBound_aboveThreshold, test_mpre201p_pressureReading_ventingRate_upperBound_belowThreshold };
enum test_mpre201p_pressureReading_ventingRate_lowerBound_values { test_mpre201p_pressureReading_ventingRate_lowerBound_aboveThreshold, test_mpre201p_pressureReading_ventingRate_lowerBound_belowThreshold };
enum test_aftLO2_lO2Level_values { test_aftLO2_lO2Level_empty, test_aftLO2_lO2Level_notEmpty };


/*  COMMANDS */ 
typedef enum { 
      test_sv33_valveCmdIn,
      test_sv03_sv_valveCmdIn,
      test_sv31_sv_valveCmdIn,
      NUM_command_types
} command_types;


/*  COMMAND TYPES */ 
enum test_sv33_valveCmdIn_values { test_sv33_valveCmdIn_open, test_sv33_valveCmdIn_close, test_sv33_valveCmdIn_noCommand };
enum test_sv03_sv_valveCmdIn_values { test_sv03_sv_valveCmdIn_open, test_sv03_sv_valveCmdIn_close, test_sv03_sv_valveCmdIn_noCommand };
enum test_sv31_sv_valveCmdIn_values { test_sv31_sv_valveCmdIn_open, test_sv31_sv_valveCmdIn_close, test_sv31_sv_valveCmdIn_noCommand };

#endif
