package LivingstoneCorba;


/**
* LivingstoneCorba/_LivingstoneEngineManagerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public class _LivingstoneEngineManagerStub extends org.omg.CORBA.portable.ObjectImpl implements LivingstoneCorba.LivingstoneEngineManager
{

  public String describe ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("describe", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return describe (        );
            } finally {
                _releaseReply ($in);
            }
  } // describe

  public LivingstoneCorba.LivingstoneCommandLine getCommandLine (String search_method, int max_candidate_classes_returned, int max_candidates_returned, int max_candidates_searched, int max_cutoff_weight, int max_history_cutoff, int max_trajectories_tracked, String progress_cmd_type, String fc_cmd_type)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCommandLine", true);
                $out.write_string (search_method);
                $out.write_long (max_candidate_classes_returned);
                $out.write_long (max_candidates_returned);
                $out.write_long (max_candidates_searched);
                $out.write_long (max_cutoff_weight);
                $out.write_long (max_history_cutoff);
                $out.write_long (max_trajectories_tracked);
                $out.write_string (progress_cmd_type);
                $out.write_string (fc_cmd_type);
                $in = _invoke ($out);
                LivingstoneCorba.LivingstoneCommandLine $result = LivingstoneCorba.LivingstoneCommandLineHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCommandLine (search_method, max_candidate_classes_returned, max_candidates_returned, max_candidates_searched, max_cutoff_weight, max_history_cutoff, max_trajectories_tracked, progress_cmd_type, fc_cmd_type        );
            } finally {
                _releaseReply ($in);
            }
  } // getCommandLine

  public LivingstoneCorba.LivingstoneCommandLine getRunningCommandLine ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRunningCommandLine", true);
                $in = _invoke ($out);
                LivingstoneCorba.LivingstoneCommandLine $result = LivingstoneCorba.LivingstoneCommandLineHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRunningCommandLine (        );
            } finally {
                _releaseReply ($in);
            }
  } // getRunningCommandLine

  public void exit ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("exit", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                exit (        );
            } finally {
                _releaseReply ($in);
            }
  } // exit

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LivingstoneCorba/LivingstoneEngineManager:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _LivingstoneEngineManagerStub
