package LivingstoneCorba;


/**
* LivingstoneCorba/Assignment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class Assignment implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;
  public int time = (int)0;

  public Assignment ()
  {
  } // ctor

  public Assignment (String _name, String _value, int _time)
  {
    name = _name;
    value = _value;
    time = _time;
  } // ctor

} // class Assignment
