package LivingstoneCorba;

/**
* LivingstoneCorba/AssignmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class AssignmentHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.Assignment value = null;

  public AssignmentHolder ()
  {
  }

  public AssignmentHolder (LivingstoneCorba.Assignment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.AssignmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.AssignmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.AssignmentHelper.type ();
  }

}
