package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneCommandLine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public interface LivingstoneCommandLine extends LivingstoneCommandLineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LivingstoneCommandLine
