package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneException extends org.omg.CORBA.UserException
{
  public int id = (int)0;
  public String description = null;

  public LivingstoneException ()
  {
    super(LivingstoneExceptionHelper.id());
  } // ctor

  public LivingstoneException (int _id, String _description)
  {
    super(LivingstoneExceptionHelper.id());
    id = _id;
    description = _description;
  } // ctor


  public LivingstoneException (String $reason, int _id, String _description)
  {
    super(LivingstoneExceptionHelper.id() + "  " + $reason);
    id = _id;
    description = _description;
  } // ctor

} // class LivingstoneException
