package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneCommandLineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public interface LivingstoneCommandLineOperations 
{
  void command (String command);
  String getHistoryTimes () throws LivingstoneCorba.LivingstoneException;
  void enableGUIUpdate ();
  void disableGUIUpdate ();

  // commands separated by \n
  void warpCommands (String commands);
  void release ();

  // this should be called finalize
  void addLivingstoneEventListener (LivingstoneCorba.LivingstoneEventListener listener) throws LivingstoneCorba.LivingstoneException;
  void removeLivingstoneEventListener (LivingstoneCorba.LivingstoneEventListener listener) throws LivingstoneCorba.LivingstoneException;
} // interface LivingstoneCommandLineOperations
