package LivingstoneCorba;

/**
* LivingstoneCorba/LivingstoneAssignmentReportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneAssignmentReportHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.LivingstoneAssignmentReport value = null;

  public LivingstoneAssignmentReportHolder ()
  {
  }

  public LivingstoneAssignmentReportHolder (LivingstoneCorba.LivingstoneAssignmentReport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.LivingstoneAssignmentReportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.LivingstoneAssignmentReportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.LivingstoneAssignmentReportHelper.type ();
  }

}
