package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneAttributeReport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneAttributeReport implements org.omg.CORBA.portable.IDLEntity
{
  public LivingstoneCorba.SingleLivingstoneAttributeReport attributes[] = null;

  public LivingstoneAttributeReport ()
  {
  } // ctor

  public LivingstoneAttributeReport (LivingstoneCorba.SingleLivingstoneAttributeReport[] _attributes)
  {
    attributes = _attributes;
  } // ctor

} // class LivingstoneAttributeReport
