package LivingstoneCorba;

/**
* LivingstoneCorba/LivingstoneCommandLineHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneCommandLineHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.LivingstoneCommandLine value = null;

  public LivingstoneCommandLineHolder ()
  {
  }

  public LivingstoneCommandLineHolder (LivingstoneCorba.LivingstoneCommandLine initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.LivingstoneCommandLineHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.LivingstoneCommandLineHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.LivingstoneCommandLineHelper.type ();
  }

}
