package LivingstoneCorba;

/**
* LivingstoneCorba/LivingstoneAttributeReportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneAttributeReportHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.LivingstoneAttributeReport value = null;

  public LivingstoneAttributeReportHolder ()
  {
  }

  public LivingstoneAttributeReportHolder (LivingstoneCorba.LivingstoneAttributeReport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.LivingstoneAttributeReportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.LivingstoneAttributeReportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.LivingstoneAttributeReportHelper.type ();
  }

}
