package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneEventListenerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

abstract public class LivingstoneEventListenerHelper
{
  private static String  _id = "IDL:LivingstoneCorba/LivingstoneEventListener:1.0";

  public static void insert (org.omg.CORBA.Any a, LivingstoneCorba.LivingstoneEventListener that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LivingstoneCorba.LivingstoneEventListener extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LivingstoneCorba.LivingstoneEventListenerHelper.id (), "LivingstoneEventListener");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LivingstoneCorba.LivingstoneEventListener read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LivingstoneEventListenerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LivingstoneCorba.LivingstoneEventListener value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LivingstoneCorba.LivingstoneEventListener narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LivingstoneCorba.LivingstoneEventListener)
      return (LivingstoneCorba.LivingstoneEventListener)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LivingstoneCorba._LivingstoneEventListenerStub stub = new LivingstoneCorba._LivingstoneEventListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LivingstoneCorba.LivingstoneEventListener unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LivingstoneCorba.LivingstoneEventListener)
      return (LivingstoneCorba.LivingstoneEventListener)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LivingstoneCorba._LivingstoneEventListenerStub stub = new LivingstoneCorba._LivingstoneEventListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
