package LivingstoneCorba;

/**
* LivingstoneCorba/LivingstoneExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.LivingstoneException value = null;

  public LivingstoneExceptionHolder ()
  {
  }

  public LivingstoneExceptionHolder (LivingstoneCorba.LivingstoneException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.LivingstoneExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.LivingstoneExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.LivingstoneExceptionHelper.type ();
  }

}
