package LivingstoneCorba;

/**
* LivingstoneCorba/LivingstoneEventListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneEventListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.LivingstoneEventListener value = null;

  public LivingstoneEventListenerHolder ()
  {
  }

  public LivingstoneEventListenerHolder (LivingstoneCorba.LivingstoneEventListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.LivingstoneEventListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.LivingstoneEventListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.LivingstoneEventListenerHelper.type ();
  }

}
