package LivingstoneCorba;


/**
* LivingstoneCorba/LivingstoneAssignmentReport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class LivingstoneAssignmentReport implements org.omg.CORBA.portable.IDLEntity
{
  public LivingstoneCorba.Assignment assignments[] = null;

  public LivingstoneAssignmentReport ()
  {
  } // ctor

  public LivingstoneAssignmentReport (LivingstoneCorba.Assignment[] _assignments)
  {
    assignments = _assignments;
  } // ctor

} // class LivingstoneAssignmentReport
