package LivingstoneCorba;

/**
* LivingstoneCorba/SingleLivingstoneAttributeReportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class SingleLivingstoneAttributeReportHolder implements org.omg.CORBA.portable.Streamable
{
  public LivingstoneCorba.SingleLivingstoneAttributeReport value = null;

  public SingleLivingstoneAttributeReportHolder ()
  {
  }

  public SingleLivingstoneAttributeReportHolder (LivingstoneCorba.SingleLivingstoneAttributeReport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LivingstoneCorba.SingleLivingstoneAttributeReportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LivingstoneCorba.SingleLivingstoneAttributeReportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LivingstoneCorba.SingleLivingstoneAttributeReportHelper.type ();
  }

}
