package LivingstoneCorba;


/**
* LivingstoneCorba/SingleLivingstoneAttributeReport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

public final class SingleLivingstoneAttributeReport implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String range[] = null;
  public String initialValue = null;

  public SingleLivingstoneAttributeReport ()
  {
  } // ctor

  public SingleLivingstoneAttributeReport (String _name, String[] _range, String _initialValue)
  {
    name = _name;
    range = _range;
    initialValue = _initialValue;
  } // ctor

} // class SingleLivingstoneAttributeReport
