package LivingstoneCorba;


/**
* LivingstoneCorba/SingleLivingstoneAttributeReportHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LivingstoneCorba.idl
* Thursday, April 20, 2006 4:53:49 PM PDT
*/

abstract public class SingleLivingstoneAttributeReportHelper
{
  private static String  _id = "IDL:LivingstoneCorba/SingleLivingstoneAttributeReport/SingleLivingstoneAttributeReport:1.0";

  public static void insert (org.omg.CORBA.Any a, LivingstoneCorba.SingleLivingstoneAttributeReport that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LivingstoneCorba.SingleLivingstoneAttributeReport extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "range",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "initialValue",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (LivingstoneCorba.SingleLivingstoneAttributeReportHelper.id (), "SingleLivingstoneAttributeReport", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LivingstoneCorba.SingleLivingstoneAttributeReport read (org.omg.CORBA.portable.InputStream istream)
  {
    LivingstoneCorba.SingleLivingstoneAttributeReport value = new LivingstoneCorba.SingleLivingstoneAttributeReport ();
    value.name = istream.read_string ();
    int _len0 = istream.read_long ();
    value.range = new String[_len0];
    for (int _o1 = 0;_o1 < value.range.length; ++_o1)
      value.range[_o1] = istream.read_string ();
    value.initialValue = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LivingstoneCorba.SingleLivingstoneAttributeReport value)
  {
    ostream.write_string (value.name);
    ostream.write_long (value.range.length);
    for (int _i0 = 0;_i0 < value.range.length; ++_i0)
      ostream.write_string (value.range[_i0]);
    ostream.write_string (value.initialValue);
  }

}
