/*
 * HistoryTablePanel.java
 *
 * Created on June 16, 2003, 2:07 PM
 */

package oliver.historytable;

/**
 *
 * @author  stephen
 */
public class HistoryTablePanel extends javax.swing.JPanel {
    
    private oliver.application.UserProperties userProperties;
    
    /** Creates new form HistoryTablePanel */
    public HistoryTablePanel(oliver.application.UserProperties userProperties) {
        this.userProperties = userProperties;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new HistoryTableModel());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setText("Search  ");
        jPanel1.add(jLabel1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.add(jTextField1);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
        ((HistoryTableModel)jTable1.getModel()).setFilter(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    public void setState(livdll.AttributeAssignment[][] state) {
        ((oliver.historytable.HistoryTableModel)jTable1.getModel()).setState(state);
        ((HistoryTableModel)jTable1.getModel()).setFilter(jTextField1.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
