/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class livdll_LivingstoneEngineJNI */

#ifndef _Included_livdll_LivingstoneEngineJNI
#define _Included_livdll_LivingstoneEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    helloWorldJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_helloWorldJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    setCBFSEngineParamsJNI
 * Signature: (IIIIIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_setCBFSEngineParamsJNI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    allocateCBFSEngineJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_allocateCBFSEngineJNI
  (JNIEnv *, jclass, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    allocateCBFSDebuggerJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_allocateCBFSDebuggerJNI
  (JNIEnv *, jclass, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    setCoverEngineParamsJNI
 * Signature: (IIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_setCoverEngineParamsJNI
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    allocateCoverEngineJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_allocateCoverEngineJNI
  (JNIEnv *, jclass, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    allocateCoverDebuggerJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_allocateCoverDebuggerJNI
  (JNIEnv *, jclass, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    deallocateEngineJNI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_deallocateEngineJNI
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    loadModelJNI
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_livdll_LivingstoneEngineJNI_loadModelJNI
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    propagateJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_propagateJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    minProgressJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_minProgressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    fullProgressJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_fullProgressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    assignMultipleJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_assignMultipleJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    unassignJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_unassignJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getPropValueJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getPropValueJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    installCandidateJNI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_installCandidateJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getFcStyleJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_livdll_LivingstoneEngineJNI_getFcStyleJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    pruneAndSearchJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_pruneAndSearchJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    findFreshJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_findFreshJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    extendJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_extendJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getSearchTerminationJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_livdll_LivingstoneEngineJNI_getSearchTerminationJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getCandidateCountJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getCandidateCountJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getCandidatePointerJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getCandidatePointerJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverCandidateAssignmentsJNI
 * Signature: (ILjava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverCandidateAssignmentsJNI
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getCandidateClassCountJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getCandidateClassCountJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getCandidateClassPointerJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getCandidateClassPointerJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverAttributeAssignmentsJNI
 * Signature: (Ljava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverAttributeAssignmentsJNI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverAttributeNamesJNI
 * Signature: (Ljava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverAttributeNamesJNI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverCommandAttributeNamesJNI
 * Signature: (Ljava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverCommandAttributeNamesJNI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverObservableAttributeNamesJNI
 * Signature: (Ljava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverObservableAttributeNamesJNI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    setAttributeModeJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_livdll_LivingstoneEngineJNI_setAttributeModeJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    createCheckpointJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_createCheckpointJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    restoreCheckpointJNI
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_livdll_LivingstoneEngineJNI_restoreCheckpointJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    deleteCheckpointJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_deleteCheckpointJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getTimeStepJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_getTimeStepJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    setTransitionVariableAtTimeJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_setTransitionVariableAtTimeJNI
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    getHistoryStartStopJNI
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_livdll_LivingstoneEngineJNI_getHistoryStartStopJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    listenerUsageJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_listenerUsageJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    parseCmdJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_livdll_LivingstoneEngineJNI_parseCmdJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    justifyPropositionJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_livdll_LivingstoneEngineJNI_justifyPropositionJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    variableValueAtTimeJNI
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_livdll_LivingstoneEngineJNI_variableValueAtTimeJNI
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    variableExogenousAtTimeJNI
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_livdll_LivingstoneEngineJNI_variableExogenousAtTimeJNI
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    printPropClausesJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_printPropClausesJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    executeWarpCommandsJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_executeWarpCommandsJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    findCandidatesJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_findCandidatesJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    assignJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_assignJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    addAssumptionJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_addAssumptionJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    mapOverPropositionStringsJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_mapOverPropositionStringsJNI
  (JNIEnv *, jobject);

/*
 * Class:     livdll_LivingstoneEngineJNI
 * Method:    findDiscrepancysJNI
 * Signature: (Ljava/util/Observer;)V
 */
JNIEXPORT void JNICALL Java_livdll_LivingstoneEngineJNI_findDiscrepancysJNI
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
