//
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES.
//
/* Generated by Together */

package gov.nasa.arc.l2tools.tools.historyTable;

import java.util.Vector;
public class SiteManager {
    /**
     *@link aggregation
     *     @associates <{gov.nasa.arc.l2tools.tools.EngineManager}>
     */
    private Vector lnkLivingstoneEngineManager;
}
