// 
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES. 
// 

/*
 * InstanceTreeTableView.java
 *
 * Created on July 29, 2002, 4:22 PM
 */

package oliver.tree;

/**
 *
 * @author  stephen
 */
public class InstanceTreeTableView extends javax.swing.JPanel {
    
    private java.util.Properties userProperties;
    private oliver.project.ProjectModel model;
    
    /** Creates new form InstanceTreeTableView */
    public InstanceTreeTableView(java.util.Properties userProperties) {
        super();
        this.userProperties = userProperties;
        initComponents();
    }
    
    public void setModel(oliver.project.ProjectModel model) {
        this.model = model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new oliver.tree.treetable.JTreeTable();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public void setComponentInstance(String name) {
        if(name.endsWith(".jmpl")) name = name.substring(0, name.length()-5);
        oliver.xmpl.Xmpl xmpl = model.getRoot().findType(name);
        if(xmpl!=null) setComponentInstance(xmpl);
    }
    
    public void setComponentInstance(oliver.xmpl.Xmpl xmpl) {
        if(xmpl instanceof oliver.xmpl.ComponentType) {
            setComponentInstance(new oliver.tree.ComponentInstance(model, (oliver.xmpl.ComponentType)xmpl));
        } else {
            System.out.println("InstanceTreeTableView.setComponentInstance() wrong class: "+xmpl.getClass().toString());
        }
    }
    
    public oliver.tree.ComponentInstance getComponentInstance() throws Exception {
        Object model = jTable1.getModel();
        if(model instanceof oliver.tree.treetable.TreeTableModelAdapter) {
            Object root = ((oliver.tree.treetable.TreeTableModelAdapter)model).getRoot();
            if(root != null && root instanceof oliver.tree.ComponentInstance) {
                return (oliver.tree.ComponentInstance)root;
            }
        }
        throw new Exception("InstanceTreeTableView.getComponentInstance() no root");
    }
    
    public void setComponentInstance(oliver.tree.ComponentInstance ci) {
        ((oliver.tree.treetable.JTreeTable)jTable1).setTreeTableModel(new InstanceTreeTableModel(ci));
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
