// 
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES. 
// 

/* Generated by Together */

package oliver.tree;

public interface ProjectModelListener extends java.util.EventListener {
    void nodeSelected(Object source, oliver.xmpl.Xmpl node);
    // Invoked after a node has changed in some way.
    void nodesChanged(Object source, oliver.xmpl.Xmpl node, String name, String newvalue, String oldvalue);
    // Invoked after nodes have been inserted into the tree.
    void nodesInserted(Object source, oliver.xmpl.Xmpl parent, int childIndex, oliver.xmpl.Xmpl child);
    // Invoked after nodes have been removed from the tree.
    void nodesRemoved(Object source, oliver.xmpl.Xmpl parent, int childIndex, oliver.xmpl.Xmpl child);
    // Invoked after the tree has drastically changed structure from a given node down.
    void everythingChanged(Object source, oliver.xmpl.Xmpl parent);
}
