#! /bin/sh
# $Id: makerecur,v 1.3 2000/09/22 22:07:16 bhudson Exp $

# USAGE: makerecur "make [args]" target [subdir1 [subdir2 ...]]
# Recursively runs make on all subdirectories.
# I was doing this everywhere, and having the problem everywhere of what
# to do when there were no subdirs; so now it's all in this script.

# This also handles makes -- like Sun make -- that don't allow -C
# while we print out with the -C syntax, we use a subshell and cd.

MAKE="$1"
TARGET="$2"
shift 2
BASEDIR=`pwd`

test $# -eq 0 && exit 0

# exit on error
set -e

for subdir in "$@" ; do
    echo ""
    echo "****************************************"
    echo "${MAKE} -C ${subdir} ${TARGET}"
    echo ""
    cd "${subdir}" 
    ${MAKE} ${TARGET} 
    cd "$BASEDIR"
done
