//
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES.
//
/* Generated by Together */

package gov.nasa.arc.l2tools.tools;

import livdll.*;

public interface EngineControlInterface {

  // public String loadModel(String filename) throws L2NativeException;

    public void minProgress(String command) throws L2NativeException;

    public void fullProgress(String command) throws L2NativeException;

    public void assign(String monitor) throws L2NativeException;

    public void findCandidates(String command) throws L2NativeException;

    public boolean propagate() throws L2NativeException;

    public Candidate[]  getCandidates();

    public Candidate[]  getCandidateClasses();

    public Attribute[] getAttributes() throws L2NativeException;

    public AttributeAssignment[][] getAttributeAssignments(Candidate c) throws IndexOutOfBoundsException, L2NativeException;

    public int getCandidateCount() throws L2NativeException;

    public String getSearchTermination() throws L2NativeException;

    public int[] getHistoryStartStop() throws L2NativeException;

    public boolean parseCmd (String cmd, String args) throws L2NativeException;

}
