//
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES.
//
/* Generated by Together */

package gov.nasa.arc.l2tools.tools;

import java.io.File;
import java.util.SortedSet;
import java.util.Vector;

public interface EngineListener {
    /**
     * A new C++ engine has been allocated for this object, possibly deallocating the previous engine. 
     */
    public void echoNewEngine(Object source, String search_method);

    /**
     * The C++ engine associated with this object has been deallocated. 
     */
    public void echoDestroyEngine(Object source);

    /**
     * A model has been loaded into the engine. 
     */
    public void echoLoadModel(Object source, String fileName, SortedSet attributes);

    /**
     * A progress command has been issued to the engine. 
     */
    public void echoCommand(Object source, String progress);

    /**
     * An assign command has been issued to the engine.  The most recent assignment will be the *first* element of the recentAssignments property on the engine bean.  (The assignments go onto the list in reverse order.) 
     */
    public void echoMonitor(Object source, String assignment);

    /**
     * A propagate command has been issued to the engine. 
     */
    public void echoPropagate(Object source, boolean consistent);

    /**
     * A findCandidates command has been issued to the engine. 
     */
    public void echoFindCandidates(Object source);

    /**
     * A findCandidates command has finished. 
     */
    public void replyFoundCandidates(Object source, Candidate[] candidates,
                                     Candidate[] distinctCandidates,
                                     Vector discrepancys,
                                     String searchTermination);

}
