//
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES.
//
/* Generated by Together */

package gov.nasa.arc.l2tools.tools;

import javax.swing.DefaultListModel;
import gov.nasa.arc.l2tools.tools.historyTable.HistoryTable;
import gov.nasa.arc.l2tools.tools.historyTable.AttributeTable;
//import gov.nasa.arc.l2tools.gui.BrowserFrame;

public class EngineManager implements ToolFactory {
    /**
     *@link aggregation
     *     @associates <{DataModel}>
     */
  private DefaultListModel engines = new DefaultListModel();
  
  public DefaultListModel getEngines() { return engines; }

  public void createDataModel(int index) {
    DataModel newBean = new DataModel();
    if(index >= engines.size())
      engines.addElement(newBean);
    else if(index < 0)
      engines.add(0, newBean);
    else 
      engines.add(index, newBean);
  }

  public void destroyDataModel(int index) throws ArrayIndexOutOfBoundsException {
      DataModel bean = (DataModel)engines.elementAt(index);
      engines.removeElementAt(index);
      bean.cleanup();
  }

  public Tool newCommandLineTool(int index) throws ArrayIndexOutOfBoundsException {
      DataModel bean = (DataModel)engines.elementAt(index);
      CommandLine cl = new CommandLine(this, bean);
      return cl;
  }

  public Tool newCandidateManagerTool(int index) throws ArrayIndexOutOfBoundsException { 
      DataModel bean = (DataModel)engines.elementAt(index);
      CandidateManager cm = new CandidateManager(this, bean);
      return cm;
  }

  public Tool newStanleyTool(int index, CommandLine commandLine) throws ArrayIndexOutOfBoundsException {
      DataModel bean = (DataModel)engines.elementAt(index);
      StanleyAdapter sa = new StanleyAdapter(bean, commandLine); 
      return sa;
  }

  public Tool newHistoryTableTool(int index) throws ArrayIndexOutOfBoundsException {
      DataModel bean = (DataModel)engines.elementAt(index);
      HistoryTable ht = new HistoryTable(bean); 
      return ht;
  }

  public Tool newAttributeTableTool(int index) throws ArrayIndexOutOfBoundsException {
      DataModel bean = (DataModel)engines.elementAt(index);
      AttributeTable at = new AttributeTable("Attribute Table", bean); 
      return at;
  }

  public Tool newControlPanelTool(int index) throws ArrayIndexOutOfBoundsException { return null; }

  public Tool newHarnessEditorTool(int index) throws ArrayIndexOutOfBoundsException { return null; }

  public Tool newTimeLineTool(int index) throws ArrayIndexOutOfBoundsException { return null; }

  public static void main(String args[]) {
    EngineManager em = new EngineManager();
    em.createDataModel(0);
    try {
      Tool cl = em.newCommandLineTool(0);
    } catch(Exception e) {
      System.out.println(e);
    }
  }

}
