//
// * See the file "l2-tools/disclaimers-and-notices.txt" for 
// * information on usage and redistribution of this file, 
// * and for a DISCLAIMER OF ALL WARRANTIES.
//
/* Generated by Together */

package gov.nasa.arc.l2tools.tools;

import java.awt.Container;

public interface Tool {

  public void setModel(DataModel model);
  public DataModel getModel();
  public Container getContainer();
}

